
-- Run this in Supabase SQL Editor to create the contact_submissions table

create table if not exists contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null,
  read boolean default false
);

-- Optional: Enable RLS (Row Level Security) if you want to restrict public access details
-- For now, since we use SERVICE_ROLE_KEY in the backend, we bypass RLS, so it's safe.
