export default function TermsPage() {
    return (
        <div className="min-h-screen bg-[#0A0A0A] text-white p-6">
            <div className="max-w-3xl mx-auto py-16">
                <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
                <p className="text-zinc-400 mb-4">Last updated: February 2, 2026</p>

                <div className="space-y-6 text-zinc-300">
                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-3">Service Description</h2>
                        <p>Persona AI provides AI-powered advisory services using simulated reasoning. All responses are generated by AI and should not be considered professional advice.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-3">Usage Limits</h2>
                        <p>Free users receive 10 messages per day. Email submission extends this to 17 messages. Premium users receive unlimited messages.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-3">Disclaimer</h2>
                        <p className="font-semibold text-white">IMPORTANT: Persona AI uses simulated reasoning and is not a human. Responses are informational only and should not be considered professional, legal, financial, or medical advice.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-white mb-3">Contact</h2>
                        <p>For questions, contact: <a href="mailto:kmish9685@gmail.com" className="text-[#FF9500] hover:underline">kmish9685@gmail.com</a></p>
                    </section>
                </div>
            </div>
        </div>
    );
}
